services:
  web:
    image: ghcr.io/tronbyt/server:2
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    init: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/app/data
    environment:
      - ENABLE_USER_REGISTRATION=false
      - SINGLE_USER_AUTO_LOGIN=false
    healthcheck:
      test: ["CMD", "/app/tronbyt-server", "health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data:
